FROM python:3.13-slim
WORKDIR /app

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt --progress-bar off

RUN adduser --disabled-password --gecos "" myuser && \
    chown -R myuser:myuser /app

ENV OTEL_RESOURCE_DETECTORS=""

COPY . .

USER myuser

EXPOSE 8080


# CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8080"]
CMD ["sh", "-c", "uvicorn main:app --host 0.0.0.0 --port 8080 --reload"]